name: 'GitHub Actions gitee'

on:
  push:
    branches: 
      - master
  schedule:
   - cron: '*/5 * * * *'
jobs:
  gitee:
    runs-on: ubuntu-latest
    steps:
    - name: Sync to Gitee
      uses: wearerequired/git-mirror-action@master
      env:
          # 注意在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY
          SSH_PRIVATE_KEY: ${{ secrets.GITEE }}
      with:
          # 注意替换为你的 GitHub 源仓库地址
          source-repo: "git@github.com:x-dr/hot.git"
          # 注意替换为你的 Gitee 目标仓库地址
          destination-repo: "git@gitee.com:goindex/hot.git"
          
