name: 'GitHub Actions gitee'

on:
  push:
    branches: 
      - master
jobs:
  result-spider:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: 'Mirror to gitee'
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: git@gitee.com:goindex/hot.git
          ssh_private_key: ${{ secrets.GITEE }}
          
