name: 'GitHub Actions gitee'

on:
  push:
    branches: 
      - master
  schedule:
   - cron: '*/5 * * * *'
jobs:
  gitee:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: 'Mirror to gitee'
        uses: x-dr/togitee@v2
        with:
          target_repo_url: git@gitee.com:goindex/hot.git
          ssh_private_key: ${{ secrets.GITEE }}
          
