name: 'GitHub Actions result'

on:
  push:
    branches: 
      - master
  schedule:
   - cron: '*/5 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Mirror the Github organization repos to Gitee.
      uses: Yikun/hub-mirror-action@v0.05
      with:
        src: github/x-dr
        dst: gitee/goindex
        dst_key: ${{ secrets.GITEESSH }}
        dst_token:  ${{ secrets.GITEE }}
        white_list: "hot"  
        force_update: true
